/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminSettingsUpdate { 
    allowedEmailDomains?: Array<string>;
    invitationExpirationHours?: number;
    passwordResetExpirationMinutes?: number;
    allowedImageTypes?: Set<AdminSettingsUpdateAllowedImageTypesEnum>;
    maximumImageBytes?: number;
    perUserStorageQuotaBytes?: number;
    imageOrphanGraceHours?: number;
}
export enum AdminSettingsUpdateAllowedImageTypesEnum {
    ImagePng = 'image/png',
    ImageJpeg = 'image/jpeg',
    ImageWebp = 'image/webp'
};



