/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminSettings { 
    allowedEmailDomains: Array<string>;
    invitationExpirationHours: number;
    passwordResetExpirationMinutes: number;
    allowedImageTypes: Array<AdminSettingsAllowedImageTypesEnum>;
    maximumImageBytes: number;
    perUserStorageQuotaBytes: number;
    imageOrphanGraceHours: number;
    noteVersionMaximumCount: number;
    noteVersionRetentionDays: number;
}
export enum AdminSettingsAllowedImageTypesEnum {
    ImagePng = 'image/png',
    ImageJpeg = 'image/jpeg',
    ImageWebp = 'image/webp'
};



