/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Re-authentication of the acting administrator. Both fields are optional in the schema and enforced by the server, so that a client which has not yet been updated fails with an application error code rather than a schema rejection. 
 */
export interface AdminStepUpRequest { 
    currentPassword?: string;
    code?: string;
}

