/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SmtpStatus } from './smtpStatus';


export interface AdminStatus { 
    service: AdminStatusServiceEnum;
    status: AdminStatusStatusEnum;
    apiVersion: AdminStatusApiVersionEnum;
    applicationVersion: string;
    buildIdentifier: string;
    database: AdminStatusDatabaseEnum;
    imageStorageBackend: AdminStatusImageStorageBackendEnum;
    imageStorage: AdminStatusImageStorageEnum;
    smtp: SmtpStatus;
    backupEnabled: boolean;
    metricsEnabled: boolean;
    jobsHealthy: boolean;
}
export enum AdminStatusServiceEnum {
    GlacierNotesCloud = 'glacier-notes-cloud'
};
export enum AdminStatusStatusEnum {
    Ok = 'ok'
};
export enum AdminStatusApiVersionEnum {
    V1 = 'v1'
};
export enum AdminStatusDatabaseEnum {
    Up = 'up',
    Down = 'down'
};
export enum AdminStatusImageStorageBackendEnum {
    Filesystem = 'FILESYSTEM',
    Postgresql = 'POSTGRESQL',
    S3 = 'S3'
};
export enum AdminStatusImageStorageEnum {
    Up = 'up',
    Down = 'down'
};



