/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminSettings { 
    instanceName: string;
    instanceLogoUrl?: string;
    defaultLanguage: AdminSettingsDefaultLanguageEnum;
    allowedEmailDomains: Array<string>;
    invitationExpirationHours: number;
    passwordResetExpirationMinutes: number;
    emailChangeExpirationMinutes: number;
    normalSessionDurationMinutes: number;
    rememberSessionDurationMinutes: number;
    allowedImageTypes: Array<AdminSettingsAllowedImageTypesEnum>;
    maximumImageBytes: number;
    perUserStorageQuotaBytes: number;
    imageOrphanGraceHours: number;
    noteVersionMaximumCount: number;
    noteVersionRetentionDays: number;
    userExportsEnabled: boolean;
    defaultTrashRetentionDays: number;
    usersMayDisableAutoPurge: boolean;
    adminDeletionRetentionDays: number;
    selfDeletionEnabled: boolean;
    publicBaseUrl: string;
    smtpSenderName: string;
    smtpSenderAddress: string;
    auditRetentionDays: number;
    operationalLogRetentionDays: number;
    loginDelayThreshold: number;
    loginLockThreshold: number;
    loginLockMinutes: number;
    commonPasswordCheckEnabled: boolean;
    passwordHistoryEnabled: boolean;
    restartRequiredSettings: Array<AdminSettingsRestartRequiredSettingsEnum>;
}
export enum AdminSettingsDefaultLanguageEnum {
    En = 'en',
    De = 'de'
};
export enum AdminSettingsAllowedImageTypesEnum {
    ImagePng = 'image/png',
    ImageJpeg = 'image/jpeg',
    ImageWebp = 'image/webp'
};
export enum AdminSettingsRestartRequiredSettingsEnum {
    ImageStorageBackend = 'imageStorageBackend',
    SmtpEnabled = 'smtpEnabled',
    BackupEnabled = 'backupEnabled',
    MetricsEnabled = 'metricsEnabled'
};



