/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminDeletionRequest { 
    mode: AdminDeletionRequestModeEnum;
    confirmation?: string;
}
export enum AdminDeletionRequestModeEnum {
    Retained = 'RETAINED',
    Immediate = 'IMMEDIATE'
};



