/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminUser { 
    id: string;
    username: string;
    email: string;
    displayName?: string;
    role: AdminUserRoleEnum;
    status: AdminUserStatusEnum;
    createdAt: string;
    lastLoginAt?: string;
    pendingDeletionAt?: string;
    deletionDueAt?: string;
    storageBytes: number;
    noteCount: number;
    notebookCount: number;
    imageCount: number;
}
export enum AdminUserRoleEnum {
    User = 'USER',
    Admin = 'ADMIN'
};
export enum AdminUserStatusEnum {
    PendingActivation = 'PENDING_ACTIVATION',
    Active = 'ACTIVE',
    Locked = 'LOCKED',
    Deactivated = 'DEACTIVATED',
    PendingDeletion = 'PENDING_DELETION',
    Deleted = 'DELETED'
};



