/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminStatus { 
    service: AdminStatusServiceEnum;
    status: AdminStatusStatusEnum;
    apiVersion: AdminStatusApiVersionEnum;
    database: AdminStatusDatabaseEnum;
}
export enum AdminStatusServiceEnum {
    GlacierNotesCloud = 'glacier-notes-cloud'
};
export enum AdminStatusStatusEnum {
    Ok = 'ok'
};
export enum AdminStatusApiVersionEnum {
    V1 = 'v1'
};
export enum AdminStatusDatabaseEnum {
    Up = 'up'
};



