/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BackupJob } from './backupJob';
import { PageMetadata } from './pageMetadata';


export interface BackupJobPage { 
    items: Array<BackupJob>;
    page: PageMetadata;
}

