/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChecklistItemView { 
    id: string;
    text: string;
    checked: boolean;
    sortOrder: number;
    createdAt: string;
    updatedAt: string;
    version: number;
}

