/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum ContentColor {

    Default = 'DEFAULT',

    Red = 'RED',

    Orange = 'ORANGE',

    Yellow = 'YELLOW',

    Green = 'GREEN',

    Teal = 'TEAL',

    Blue = 'BLUE',

    Purple = 'PURPLE',

    Pink = 'PINK',

    Gray = 'GRAY'
}

