/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImageMetadata { 
    id: string;
    mimeType: ImageMetadataMimeTypeEnum;
    byteSize: number;
    width: number;
    height: number;
    thumbnailMimeType: ImageMetadataThumbnailMimeTypeEnum;
    thumbnailByteSize: number;
    thumbnailWidth: number;
    thumbnailHeight: number;
    contentUrl: string;
    thumbnailUrl: string;
    createdAt: string;
}
export enum ImageMetadataMimeTypeEnum {
    ImagePng = 'image/png',
    ImageJpeg = 'image/jpeg'
};
export enum ImageMetadataThumbnailMimeTypeEnum {
    ImagePng = 'image/png',
    ImageJpeg = 'image/jpeg'
};



