/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InitialAdministratorRequest { 
    username: string;
    email: string;
    displayName?: string;
    password: string;
    language?: InitialAdministratorRequestLanguageEnum;
}
export enum InitialAdministratorRequestLanguageEnum {
    En = 'en',
    De = 'de'
};



