/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvitationInspection { 
    emailHint: string;
    proposedUsername?: string;
    displayName?: string;
    expiresAt: string;
}

