/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MfaChallenge { 
    token: string;
    expiresAt: string;
    attemptsRemaining: number;
    acceptedFactors: Array<MfaChallengeAcceptedFactorsEnum>;
}
export enum MfaChallengeAcceptedFactorsEnum {
    Totp = 'TOTP',
    RecoveryCode = 'RECOVERY_CODE'
};



