/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MfaEnrollmentStart { 
    /**
     * Grouped uppercase Base32
     */
    secret: string;
    /**
     * otpauth:// URI, the only value a QR renderer receives.
     */
    provisioningUri: string;
    expiresAt: string;
    digits: number;
    periodSeconds: number;
}

