/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A single code field accepts either a TOTP code or a recovery code. The two are deliberately not distinguished, so that a failure discloses nothing about which was attempted. 
 */
export interface MfaLoginRequest { 
    challengeToken: string;
    code: string;
}

