/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MfaStatus { 
    status: MfaStatusStatusEnum;
    confirmedAt?: string;
    recoveryCodesRemaining?: number;
}
export enum MfaStatusStatusEnum {
    None = 'NONE',
    Pending = 'PENDING',
    Active = 'ACTIVE'
};



