/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum NoteVersionReason {

    EditorClose = 'EDITOR_CLOSE',

    Periodic = 'PERIODIC',

    Conflict = 'CONFLICT',

    TrashRestore = 'TRASH_RESTORE',

    VersionRestore = 'VERSION_RESTORE'
}

