/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './pageMetadata';
import { NoteVersionSummary } from './noteVersionSummary';


export interface NoteVersionPage { 
    items: Array<NoteVersionSummary>;
    page: PageMetadata;
}

