/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NoteVersionReason } from './noteVersionReason';
import { NoteType } from './noteType';
import { ContentColor } from './contentColor';
import { ChecklistItemInput } from './checklistItemInput';


export interface NoteVersion { 
    id: string;
    noteId: string;
    sourceVersion: number;
    reason: NoteVersionReason;
    snapshotAt: string;
    noteType: NoteType;
    title: string;
    content: string;
    checklistItems: Array<ChecklistItemInput>;
    pinned: boolean;
    archived: boolean;
    color: ContentColor;
    labelIds: Array<string>;
    imageIds: Array<string>;
}



