/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NoteVersionReason } from './noteVersionReason';
import { NoteType } from './noteType';


export interface NoteVersionSummary { 
    id: string;
    noteId: string;
    sourceVersion: number;
    reason: NoteVersionReason;
    snapshotAt: string;
    noteType: NoteType;
    title: string;
}



