/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PingResponse { 
    service: PingResponseServiceEnum;
    status: PingResponseStatusEnum;
    apiVersion: PingResponseApiVersionEnum;
    serverTime: string;
}
export enum PingResponseServiceEnum {
    GlacierNotesCloud = 'glacier-notes-cloud'
};
export enum PingResponseStatusEnum {
    Ok = 'ok'
};
export enum PingResponseApiVersionEnum {
    V1 = 'v1'
};



