/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationError } from './validationError';


export interface ProblemDetails { 
    type: string;
    title: string;
    status: number;
    detail: string;
    instance?: string;
    correlationId: string;
    errorCode: string;
    validationErrors?: Array<ValidationError>;
}

