/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthenticatedUser } from './authenticatedUser';
import { SessionSummary } from './sessionSummary';


export interface SessionContext { 
    user: AuthenticatedUser;
    session: SessionSummary;
}

