/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SessionSummary { 
    id: string;
    current: boolean;
    rememberMe: boolean;
    createdAt: string;
    lastSeenAt: string;
    expiresAt: string;
    clientDescription?: string;
}

