/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SmtpStatus { 
    configured: boolean;
    senderName: string;
    senderAddress: string;
    state: SmtpStatusStateEnum;
    lastSuccessfulAt?: string;
    lastFailureCategory?: SmtpStatusLastFailureCategoryEnum;
}
export enum SmtpStatusStateEnum {
    NotConfigured = 'NOT_CONFIGURED',
    Ready = 'READY',
    Succeeded = 'SUCCEEDED',
    Failed = 'FAILED'
};
export enum SmtpStatusLastFailureCategoryEnum {
    Connection = 'CONNECTION',
    Authentication = 'AUTHENTICATION',
    Tls = 'TLS',
    Delivery = 'DELIVERY',
    Unknown = 'UNKNOWN'
};



