/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransferCounts { 
    notebooks: number;
    notes: number;
    labels: number;
    images: number;
    checklistItems: number;
}

