/**
 * Glacier Notes Cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransferCounts } from './transferCounts';


export interface TransferJob { 
    id: string;
    kind: TransferJobKindEnum;
    state: TransferJobStateEnum;
    phase?: TransferJobPhaseEnum;
    counts?: TransferCounts;
    hasConflicts?: boolean;
    quotaImpactBytes?: number;
    errors?: Array<string>;
    downloadUrl?: string;
    createdAt: string;
    completedAt?: string;
    expiresAt: string;
}
export enum TransferJobKindEnum {
    Export = 'EXPORT',
    Import = 'IMPORT'
};
export enum TransferJobStateEnum {
    Queued = 'QUEUED',
    Running = 'RUNNING',
    Ready = 'READY',
    Succeeded = 'SUCCEEDED',
    Failed = 'FAILED',
    Canceled = 'CANCELED',
    Expired = 'EXPIRED'
};
export enum TransferJobPhaseEnum {
    Generate = 'GENERATE',
    Inspect = 'INSPECT',
    Apply = 'APPLY'
};



