export * from './administration.service';
import { AdministrationService } from './administration.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './currentUser.service';
import { CurrentUserService } from './currentUser.service';
export * from './images.service';
import { ImagesService } from './images.service';
export * from './labels.service';
import { LabelsService } from './labels.service';
export * from './notebooks.service';
import { NotebooksService } from './notebooks.service';
export * from './notes.service';
import { NotesService } from './notes.service';
export * from './sessions.service';
import { SessionsService } from './sessions.service';
export * from './setup.service';
import { SetupService } from './setup.service';
export * from './system.service';
import { SystemService } from './system.service';
export * from './transfers.service';
import { TransfersService } from './transfers.service';
export const APIS = [AdministrationService, AuthenticationService, CurrentUserService, ImagesService, LabelsService, NotebooksService, NotesService, SessionsService, SetupService, SystemService, TransfersService];
